public class ConstantsUtilities {
    public static final String GAS = 'gas';
    public static final String WATER = 'water';
    public static final String ELECTRICITY = 'electricity';

    public static final String DNIPRO = 'Dnipro';
    public static final String KROPYVNYTSKYY = 'Kropyvnytskyy';
    public static final String KHARKIV = 'Kharkiv';
    public static final String MARIUPIL = 'Mariupil';
    public static final String KYIV = 'Kyiv';
    public static final String CHERNIGIV = 'Chernigiv';
    public static final String ODESA = 'Odesa';
    public static final String KHERSON = 'Kherson';
    public static final String LVIV = 'Lviv';
    public static final String UZGOROD = 'Uzgorod';

    public static final String CENTER = 'Center';
    public static final String EAST = 'East';
    public static final String NORTH = 'North';
    public static final String SOUTH = 'South';
    public static final String WEST = 'West';

    public static final Map<String,String> mapOfCities = new Map<String, String>{
        'Dnipro' => 'Dnipro',
        'Kropyvnytskyy' => 'Kropyvnytskyy',
        'Kharkiv' => 'Kharkiv',
        'Mariupil' => 'Mariupil',
        'Kyiv' => 'Kyiv',
        'Chernigiv' => 'Chernigiv',
        'Odesa' => 'Odesa',
        'Kherson' => 'Kherson',
        'Lviv' => 'Lviv',
        'Uzgorod' => 'Uzgorod'
    };    
}