public class ConstantsErrorMessage {
    
    public static final String BLANK_FIELD_ON_LOGIN_PAGE = 'One of the fields was empty. Please fill in both fields Phone and Password';
    public static final String INVALID_VALUE = 'Verify that the Phone or Password are entered correctly';
    
    public static final String FILL_FIELD_CITY = 'Please enter a value in the Required Field - City';
    public static final String EMPTY_FIELDS = 'One of the fields was empty. Please fill all Fields';
    public static final String DUPLICATED_MOBILE = 'User with such Mobile is already registered. Please enter a valid Mobile.';
    public static final String PASSWORD_NOT_CONFIRMED = 'The passwords you entered do not match. Please try again.';
    public static final String EMAIL_INVALID = 'The email address was entered in the wrong format. Please enter a valid email.';
    public static final String PASSWORD_INVALID = 'Password must contain minimum eight characters, at least one letter and one number';
    public static final String FIRSTNAME_INVALID = 'Please enter a valid First name';
    public static final String LASTNAME_INVALID = 'Please enter a valid Last name';
    
    public static final String EMPTY_FIELD_MOBILE = 'Mobile field is empty. Please enter a mobile.';
    public static final String MOBILE_NOT_FOUND = 'No mobile user has been registered for this mobile number. Please check the entered mobile';

}