public class UtilityPaymentStructure {
    
    public Decimal totalAmount;
    public Decimal electricityAmount;
    public Decimal gasAmount;
    public Decimal waterAmount;
    public Decimal totalCountElectricity;
    public Decimal totalCountGas;
    public Decimal totalCountWater;
    public String userName;
    public Id userId;
    public String region;
    public Datetime datePay;
    public String email;
    
 }